info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: "${spring-profiles.active}"
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/benchdb
    username: root
    password: k1n6h05t
  jpa:
    hibernate:
      ddl-auto: update
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
server:
  port: 1001